### ISSUE TITLE
Crawler attributes like `data-elastic-include` are ignored

### ISSUE THREAD

**Issue by sarahg** [elastic/crawler#152]
### To Reproduce
1. Create a web crawler
2. Set it up to crawl a site that has pages with a `data-elastic-include` tag. Feel free to use our project, https://new.docs.gitlab.com if you'd like. Interior content pages have a `data-elastic-include` attribute on the main content div.
3. After the index builds, view a document in the index (https://your-endpoint.biz/app/enterprise_search/content/search_indices/search-your-index-name/documents).
4. You should see content outside of the `data-elastic-include` inside the `body_content` field.

## Expected behavior

Behavior described in the [docs](https://www.elastic.co/guide/en/enterprise-search/current/crawler-content.html#crawler-content-inclusion-and-exclusion):

> For all pages that contain HTML tags with a data-elastic-include attribute, the crawler will only index content within those tags.

## Screenshots

**Markup**

![Image](https://github.com/user-attachments/assets/8d81de99-3dd5-4cb8-88dc-26819667e2aa)

**Index contents**

![Image](https://github.com/user-attachments/assets/cfc1d191-283c-4c70-8b8d-4bc0b62da6bd)

**Impact**

![Image](https://github.com/user-attachments/assets/eeee251f-24df-4309-ab3c-efdff7b6fa79)

## Environment

n/a

## Additional context

We're using the web crawler with Elasticsearch on Elastic Cloud.

**Attempted workaround**: Tried getting around this by using another data attribute to create a custom field as described [here](https://www.elastic.co/guide/en/enterprise-search/current/crawler-content.html#crawler-content-meta-tags-content-extraction). Seems like something special must happen when processing `body_content`, though. My new field didn't get spaces between HTML elements like `body_content` does, so snippets from that aren't as readable, they look sort of broken:

| Custom field snippets (no spaces between elements in the snippets) | `body_content` snippets |
| --- | --- |
| ![Image](https://github.com/user-attachments/assets/cc36f325-1bf2-410e-87ff-f86421981860) | ![Image](https://github.com/user-attachments/assets/c7f7ad8d-9932-4d24-a935-24609d76dc77) |

**Comment by navarone-feekery** [comment]
Hi @sarahg! Thanks for submitting this bug report. In the issue you say you were using Elastic Crawler on Cloud, which is different from this project (Open Crawler). However, coincidentally they share the same code when it comes to data exclusion/inclusion tags, so I'll answer here instead of moving the issue.

Based on what I can see in the screenshots you've provided, I think the tags are working as expected. However, the docs are clearly wrong here and we need to fix them.

What is missing is a higher-level `data-elastic-exclude` tag to prevent other divs from being extracted.
To back up my claim, you can look at the [second docs example](https://www.elastic.co/guide/en/enterprise-search/current/crawler-content.html#crawler-content-inclusion-and-exclusion-examples):

```
<body>
  test1
  <div data-elastic-exclude>
    test2
    <p data-elastic-include>
      test3
      <span data-elastic-exclude>
        test4
        <span data-elastic-include>test5</span>
      </span>
    </p>
    test6
  </div>
  test7
</body>
```

This will extract the values `test1` and `test7` even though there is a `data-elastic-include` tag in the DOM, because there is no higher `data-elastic-exclude` tag preventing extraction from the `body` element.

For your case, if you alter your DOM to have a `data-elastic-exclude` tag in a high element like below, it should work:

```
<body>
  <main>
    <nav data-elastic-exclude></nav>
    <div data-elastic-exclude class="template-single"> <!-- add tag to this div -->
      <div class="main-content">
        <div class="docs-content">
          <div data-elastic-include></div>
          <div data-elastic-exclude class="help-feedback"></div>
        </div>
      </div>
    </div>
  </main>
</body>
```

Sorry for the incorrect documentation. Let me know if the above fix works.
If there's more to the DOM that I can't see in the screenshots and the fix doesn't work, let me know and I'll investigate further.
In the meantime I'll fix the documentation.

**Comment by sarahg** [comment]
@navarone-feekery Thanks for taking a look, even though this was the wrong issue queue! :) Adding an outer `data-elastic-exclude` tag solved the problem, so this was indeed just a docs problem. I'll go ahead and close this.

**Comment by navarone-feekery** [comment]
Glad that it helped!
The documentation has also been updated, [hopefully it's clearer now](https://www.elastic.co/guide/en/enterprise-search/current/crawler-content.html#crawler-content-inclusion-and-exclusion) (might need a cache clear to be visible).
