### ISSUE TITLE
Add configuration parameters to limit crawled paths (allow / disallow)

### ISSUE THREAD

**Issue by simonhearne** [elastic/crawler#54]
### Problem Description

The crawler should provide the ability to allow / disallow paths on a domain, e.g.:
```
  allowed_paths:
    - /help/
    - /support/
  disallowed_paths:
    - /account/
    - /user/
```

### Proposed Solution

Either a simple `path contains` rule as described above (with assumed surrounding wildcards) or a regex pattern match that can be provided in crawler.yml configuration files.

Official doc link from [similar capability in Elastic crawler](https://www.elastic.co/guide/en/enterprise-search/current/crawler-managing.html#crawler-managing-crawl-rules)

**Comment by jeffvestal** [comment]
This would be extremely helpful. 

For example, if I want to crawl just [Search Labs](https://www.elastic.co/search-labs), I get linked out to /blog, our docs, and other language paths such as /cn.

**Comment by jeffvestal** [comment]
Here is a visual of my struggle. 
I'm crawling search, observability, and security labs, and I'm spending more time and resources crawling pages I have no interest in. Not to mention inference time since I'm indexing them into a semantic_text field. 

![CleanShot 2024-07-15 at 15 44 15@2x](https://github.com/user-attachments/assets/e04c2d2b-1a1a-4615-b3b0-be008914931d)
